on:
  push:
    branches:
      - sync
  pull_request:
  schedule:
    - cron: '0 0 */1 * *'

name: Sync

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Fetch upstream
        run: |
          git clone --depth=1 https://github.com/rollup/rollup
      - name: Generate SUMMARY
        run: |
          set -x
          mkdir -p rollup/docs/.github/workflows
          cp -a .github/workflows/gitbook.yaml rollup/docs/.github/workflows/
          cp book.json rollup/docs
          cd rollup/docs
          mv 00-introduction.md README.md
          npm init -f
          npm install gitbook-summary
          npx book sm -t "[Rollup 英文文档](https://github.com/rollup/rollup)" -i node_modules
          rm -rf node_modules package.json package-lock.json
          ls -la
      - name: Push docs src
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: docker://pcit/pages
        env:
          PCIT_EMAIL: khs1994@khs1994.com
          PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
          PCIT_GIT_URL: github.com/khs1994-website/rollup-docs.us-en
          PCIT_KEEP_HISTORY: "true"
          PCIT_LOCAL_DIR: rollup/docs
          PCIT_MESSAGE: Sync from rollup/rollup by PCIT ${{ github.sha }}
          PCIT_TARGET_BRANCH: master
          PCIT_USERNAME: khs1994
